[package]
name = "lzarc"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[dependencies]
binread = "2.1.1"
rust_lzss = { git = "https://github.com/jam1garner/rust_lzss" }
